apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  namespace: ${BRANCH_NAME}
  labels:
    app: backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
      - name: backend-api
        image: abdelrahman58/badreadsbackend-$BRANCH_NAME-$BUILD_NUMBER
        ports:
        - containerPort: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: ${BRANCH_NAME}
spec:
  selector:
    app: backend-api
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
