apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jenkins
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      #securityContext:
      #  fsGroup: 1000 
      #  runAsUser:1000
      containers:
      - image: jenkins/jenkins:lts-jdk11   #jenkins/jenkins
        name: jenkins
        resources: {}
        ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 5000
            protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /login
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 2
          timeoutSeconds: 5
        volumeMounts:
          - mountPath: /var/jenkins_home
            name: jenkins-home
      volumes:
      - name: jenkins-home
        #hostPath:
        #  path: /home/abdelrahman/jenkins

        persistentVolumeClaim:
          claimName: jenkins-pvc