apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins
  name: jenkins-ubuntu-slave-svc
spec:
  ports:
  - name: jenkins-ubuntu-slave
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    app: jenkins-slave
  type: ClusterIP
